### ISSUE TITLE
[New Data Request Form]: 

### ISSUE THREAD

**Issue by Joseallencali** [tellor-io/dataSpecs#113]
### Contact Details

joseallen.cali@gmail.com

### Just need a new Spot Price?

CRV/USD. Every 1 hours, or price fluctuation exceeds 5%. Binance, coinbase, coinmarketcap, coingecko

### Query Type Name

SpotPrice

### Description

This data is requested mainly to determine the price information in the agreement and make some extensions on this basis.
I hope I can use it on goerli and mainnet later.

### Your query parameters

1. asset
    - description: CRV
    - value type: `string`
2. currency
    - description: USD
    - value type: `string`

### Your response type

- abi_type: ufixed256x18 (18 decimals of precision) - packed: false ```

**Comment by spuddyminer** [comment]
Hello @Joseallencali ! CRV/USD spot price is already available. Here is an example report: 
https://goerli.etherscan.io/tx/0x745d0019d9d5c4d223d45c317faa5344e7ca560f52c82b915fc5ac7d77d66751

We always have reporters running on the testnets that are ready to submit any tipped values. To learn about tipping / requesting data updates on Tellor, check out the docs here: https://docs.tellor.io/tellor/getting-data/funding-a-feed

Let us know if you need any help integrating tellor!

**Comment by spuddyminer** [comment]
also, you'll need some testnet TRB. feel free to drop your address here with the network that you want to use, or find me on discord 🤙

**Comment by Joseallencali** [comment]
I don't fully understand the tipping mechanism, I can send a single or recurring price request for the spot price of CRV/USD on the mainnet, but if someone has already tipped the spot price, I don't need to tip. Is this the correct way to use it?
Are there spot prices that don't require tipping?

**Comment by Joseallencali** [comment]
I don't fully understand the tipping mechanism, I can send a single or recurring price request for the spot price of CRV/USD on the mainnet, but if someone has already tipped, I don't need to tip. Is this the correct way to use it?
Are there spot prices that don't require tipping?

**Comment by spuddyminer** [comment]
You can see what reporters are updating here: https://tellor.io/data-feed/. 

Long story short, tipping is not required. However if you want to have a secure and decentralized data-feed, tipping is the best way to do this. Tips guarantee that reporters will be racing to submit the data that you need when you need it.

Tellor is an open oracle. Anyone can stake TRB and report data, so if you don't want to tip you could always run the telliot client yourself as a project. Just be aware that you're only relying on the Tellor's dispute system / governance to secure and decentralize your data feed. 

I think it makes sense to close this issue since we can already provide a medianized crv/usd spot price with the telliot client. You can find me on Discord I'm spuddy.eth#2499, or on telegram @spuddyminer. Where can we contact you? email?

**Comment by Joseallencali** [comment]
OK. I almost understand. I need to continue to evaluate. If there are more questions, I will go to discord to find you. Thank you.
