### ISSUE TITLE
New Price Feed: USD:BRL

### ISSUE THREAD

**Issue by evandrosaturnino** [tellor-io/dataSpecs#121]
### Contact Details

evandro.saturnino@gmail.com

### Just need a new Spot Price?

BRL/USD

### Description

BRL:USD price feed

**Comment by spuddyminer** [comment]
Thanks @evandrosaturnino ! 
We will need to get a bit more granular about what exactly you're looking for. I think by "BRL" you mean the Brazilian Real, is that correct?  

Should it be calculated as [BRL/USD](https://finance.yahoo.com/quote/BRLUSD=X?p=BRLUSD=X&.tsrc=fin-srch)? or [USD/BRL](https://finance.yahoo.com/quote/BRL=X/?guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAALidX49_qdkYOLYO0TNR585UlRA9rTv4yw4YzxVdFeDfFK8uaQcyxpxyRe8rBMeeyEM97bXbC2oDTKrgvIkgmcvyTTyEBZJcN0dLvP9_clbskqP-yc9mzhY-70kfGQmYEvWy4ylqMcqrhSw02YClEV0cwaxpYS9Vcnfwh7acRtmV)?

**Comment by spuddyminer** [comment]
Here is an example report for BRL/USD https://sepolia.etherscan.io/tx/0xccfc96482a038953518327785c46a4ddf2d9
![Screenshot 2023-06-20 at 10 49 27 AM](https://github.com/tellor-io/dataSpecs/assets/72078372/524477a5-c9c1-45ca-ac5b-c1467403ccce)
e5b48c1c4d1759b06b043fd60d16

**Comment by evandrosaturnino** [comment]
@spuddyminer yes, that's correct. BRL stands for Brazilian Real. Should be BRL/USD, please.

**Comment by spuddyminer** [comment]
@evandrosaturnino Here is the pull request to add the BRL/USD feed to telliot:

https://github.com/tellor-io/telliot-feeds/pull/687

I'm going to go ahead and close this issue, since we successfully added the new spot price. If you have any questions or comments, feel free to reach out anytime. Also, let us know when you're ready to coordinate your integration in more detail. Tellor is an open network, so we can help as much or as little as you'd like. Thanks!
