### ISSUE TITLE
New custom data for Cue

### ISSUE THREAD

**Issue by sunosuporno** [tellor-io/dataSpecs#79]
### Cue is a hackathon project for Ethglobal '22. We are trying to build the notification OS for web3. 

* Summary: The API shows whether a user has opted for accepting a product's notifications.
* Information: Adds the ability to query Tableland for a particular user and product and return a yes/no value
* Return Value: bool
* Supported API: https://cue-tellor.vercel.app/query/:table/:company/:wallet_address
Eg. https://cue-tellor.vercel.app/query/notifs_allowlist_80001_2035/cue_test/43690047485523017521719660013406923964685528852

**Comment by themandalore** [comment]
Hey @sunosuporno !  Thanks for the PR.  I'll work with the guys on getting it up, but just so you know, it looks like a centralized API right?  If there's no alternative way to get the data, this means that if this API goes down, then you'll be out of luck in terms of correct data

**Comment by sunosuporno** [comment]
Hey @themandalore, the data comes from Tableland, so it's open-source. Basically, I use this: [API of Tableland](https://testnet.tableland.network/query?mode=json&s=select%20*%20from%20notifs_allowlist_80001_2035%20where%20company_name%20=%20%27cue_test%27%20and%20wallet_address%20=%20%2743690047485523017521719660013406923964685528852%27) and see if I get back an array. If there's an array, I send 1, otherwise 0. The backend is basically there to do that 1 or 0 sending in Json. If you can help set it up in a more correct way, I would be happy! Though there's not much time. Would appreciate you reaching out at Suporno#3903 on Discord

**Comment by oraclown** [comment]
@sunosuporno Here's an example of that data reported to a tellor oracle on polygon testnet: https://mumbai.polygonscan.com/tx/0x8bdc4ddd6400cac9f85ac0c81f62d3843339025183b5567bcf6da3db7d1c5f76

I used the `NumericApiResponse` type with the `url` being the example you provided above and a `parseStr` of `"message"`.

You would read the value from the oracle using `getCurrentValue` and the query ID (unique identifier of your data) `0x d0066ccb8364e71fba623e3bc051c4cb1a397d81680f719fbfed5ccbb6e810f5`. Keep in mind that it'll return `1 * 10**18` once you decode the response, because it has 18 decimals of precision.

You can decode the query data and submitted value bytes using this tool as well if you need: https://querydataapi.herokuapp.com/docs

**Comment by tkernell** [comment]
It seems this doesn't need a custom query type at this point. While it just uses a single API source, the `NumericApiResponse` should work. If more sources become available, then a new query type can be created. I will be closing this in the next few days unless anyone objects.

**Comment by oraclown** [comment]
> It seems this doesn't need a custom query type at this point. While it just uses a single API source, the `NumericApiResponse` should work. If more sources become available, then a new query type can be created. I will be closing this in the next few days unless anyone objects.

2nd. If a more robust solution is needed with multiple, specific sources, then check out [creating a new query type](https://github.com/tellor-io/dataSpecs#create-new-query-type). Closing
